### ISSUE TITLE
Does not work with Gtile on Gnome 3.34.1/Pop!_OS 19.10 on corners

### ISSUE THREAD

**Issue by mineben256** [poehlerj/no-title-bar#6]
On gnome-terminal on Gnome 3.34.1 on Pop!_OS 19.10 I am unable to hide the gnome-terminal's title bar when snapping it to a corner. However, I am able to use it fine when I snap it to the side with win+numpad(2,4,6,8) and then continue pressing win+numpad(2,4,6,8) to toggle it through various sizes. When pressing win+numpad(1,3,7,9) however, it never seems to hide the title bar.  

![Screenshot from 2020-02-06 19-23-55](https://user-images.githubusercontent.com/33190427/73990276-aa178e00-4916-11ea-9bb2-9255c40f7f1a.png)
![Screenshot from 2020-02-06 19-26-20](https://user-images.githubusercontent.com/33190427/73990280-ae43ab80-4916-11ea-8ad3-17fee645c628.png)

I have a two-monitor setup and the titlebar hides on neither of the monitors. I installed both extensions through the Gnome Shell Extensions Firefox extension.

**Comment by poehlerj** [comment]
I actually didn't know, you can snap windows to the corner of a display and was unable to reproduce this. Is it possible, you are using an extension like this: https://extensions.gnome.org/extension/39/put-windows/?

**Comment by mineben256** [comment]
Yes, I was using that precise extension.

**Comment by poehlerj** [comment]
Inter-Op with other gnome extensions is always a bit of a hassle. Not only is gnome-shell's API changing at a very high speed, other extensions do as well. I'm not really convinced, this extension should be able to work together with `put-windows`.
The next thing is what you would expect the titlebar doing when you snap the windows to corners. Gnome after all is not a tiling window manager (unless you install some extensions) and so I would expect that the titlebar would still be there in order to distinguish between different windows. There might still be a inconsistency with vertical split, as you already described, but that is probably something I personally got used to. For this reason, if you would like to have a correct implementation for Inter-Op you should have the option to change the behavior in the extension's settings, so users don't get confused.
I'm personally not using put-windows and so am not really willing maintaining special implementations for it. For sure you could implement your own solution in a fork, but unfortunately for you I see nothing productive, I can do on my side.

**Comment by mineben256** [comment]
Ok, thanks for your comments.

**Comment by lpryszcz** [comment]
Same issue here. But if I have to choose, I'll stick with no-title-bar-forked as it's more useful for me. Great work, thanks!
